### ISSUE TITLE
PyPiVersion returns the wrong version for "beta" branch

### ISSUE THREAD

**Issue by gadgetchnnel** [ludeeus/pyhaversion#10]
**Is your feature request related to a problem? Please describe.**
PyPiVersion is returning the wrong version number (99.3) for the "beta" branch.
I'd reported this over at the Home Assistant repo (https://github.com/home-assistant/home-assistant/issues/32268) but the issue appears to be with this package.

**Describe the solution you'd like**
Should return the latest beta version (which was 0.106.b5 at the time I tested this).

**Describe alternatives you've considered**

**Additional context**

Appears to be due to using the built-in **sorted** function to sort the releases by version in descending order and, with a simple alphanumeric sort, 0.99.3 is treated as the latest version.

It looks like this can be fixed by using the **natsorted** function from the [natsort](https://pypi.org/project/natsort/) package instead which applied a "natural" sorting and seems to pick up the correct version.

**Comment by gadgetchnnel** [comment]
@ludeeus Realised that I added this as a feature request, when it should be an issue.

**Comment by ludeeus** [comment]
https://github.com/ludeeus/pyhaversion/releases/tag/3.3.0
