### ISSUE TITLE
HAIO option doesn't work

### ISSUE THREAD

**Issue by mdegat01** [ludeeus/pyhaversion#11]
**Describe the bug**
I tried to use the [version sensor](https://www.home-assistant.io/integrations/version/) in home assistant with source set to `haio` and I received this message in my logs:
**log**
```
2020-06-08 12:50:48 CRITICAL (MainThread) [pyhaversion] Something really wrong happened! - Expecting value: line 1 column 1 (char 0)
```
I looked in the source here and it seems when trying to use pyhaversion with source of `haio` it tries to use the URL [https://www.home-assistant.io/version.json](https://www.home-assistant.io/version.json) to get the version info.  This URL does not return JSON though, it returns HTML with JSON inside it. 

I'm not sure what broke, seems like either the website needs to be fixed so it serves up JSON again, the library needs to change the URL it uses or the `haio` option needs to be removed.

**Comment by hmmbob** [comment]
Not an issue here, but in the HA website. Fix here: https://github.com/home-assistant/home-assistant.io/pull/13699

**Comment by ludeeus** [comment]
That is correct 👍
