### ISSUE TITLE
Add support for querying the ghcr.io version

### ISSUE THREAD

**Issue by thislooksfun** [ludeeus/pyhaversion#133]
## The idea

Currently there is support for querying the Docker Hub version, but according to the hass website, the preferred way to get the docker images is from ghcr.io (see the first entry under ["Breaking Changes"](https://www.home-assistant.io/blog/2023/07/05/release-20237/#breaking-changes) in the 2023.7 release notes). It would be ideal if I can track that version, rather than the one on Docker Hub.

## Implementation

I haven't read the code, but I imagine it would be a clone of the existing Docker Hub code but with a different url.

## Alternatives

The Docker Hub version is an ok proxy for now, but I'd rather not mix-and-match sources if I can help it.

**Comment by ludeeus** [comment]
There is no API for that.
