### ISSUE TITLE
PyPiVersion wrong beta versions if there are more than 10 beta releases

### ISSUE THREAD

**Issue by gadgetchnnel** [ludeeus/pyhaversion#16]
**Describe the bug**

When using the "beta" branch for PyPi, if the beta has more than 10 releases, for example 0.115 which is currently at 0.115.0b11, the wrong version is returned (in this case 0.115.0b9). It would appear that the beta part of the version number is being sorted alphanumerically resulting in 0.115.0b11 (and 0.115.0b10) coming before 0.115.0b9

**log**
```
Add your logs here.
```

**Comment by ludeeus** [comment]
Fixed in 3.4.2 <https://github.com/ludeeus/pyhaversion/releases/tag/3.4.2>
