### ISSUE TITLE
raspberrypi4 and raspberrypi4-64 images

### ISSUE THREAD

**Issue by Sennevds** [ludeeus/pyhaversion#7]
If you look at the documentation off Home Assistant(https://www.home-assistant.io/integrations/version/#supported-images-for-hassio-and-docker) it looks like raspberrypi4 and raspberrypi4-64 images are included but this script doesn't include them.
Would it be possible to include these?

**Comment by heinoldenhuis** [comment]
I am having the same issue that the images are missing for this component, log:
2020-01-17 09:08:34 WARNING (MainThread) [pyhaversion] raspberrypi4 is not a valid image using default
